### ISSUE TITLE
Bug: Feed has no items and wrong name

### ISSUE THREAD

**Issue by hyperfekt** [GetStream/Winds#41] opened 2016-11-19 12:58 UTC
When subscribing to this feed: http://www.feed43.com/bloomberg_view.xml
its' title shows up as 'Bloomberg Technology' instead of 'Bloomberg View' and contains no items. If you check the actual feed, you will notice the discrepancy.
What could cause this bug?

**Comment by Wowl** [comment] 2016-11-19 14:32
Another one with the wrong name (of a different section) is this one: http://feeds.feedburner.com/nymag/intelligencer (it shows up as 'selectall', which is NYMag as well but has different articles: http://feeds.feedburner.com/nymag/selectall)

**Comment by tschellenbach** [comment] 2016-11-21 23:45
The problem is that we're using the site name instead of a feed name... We'll probably pick this up in 0.3.0, a pull request is always appreciated :)

**Comment by dwightgunning** [comment] 2017-01-16 23:19
I like @hyperfekt's proposal in Issue #39 to let user's update feed names. That said we should fix this all the same. I'll take a look at this first.

**Comment by dwightgunning** [comment] 2017-01-18 20:18
I'm actually struggling to replicate this.

AFAICS the feed title used within the Stream UI is set at SitesController:39-44 right after the DiscoverService.findRSS() returns discovers and extracts the metadata associated with the feed. 

Git blame shows this block has changed since prior to the bug being raised. So perhaps I'm looking at this wrongly?

Currently I'm able to import the two example feeds posted by @hyperfekt and the Stream UI shows the same titles that appear in the `<title>` tag within the raw feed.

**Comment by nparsons08** [comment] 2017-09-20 20:26
Since there hasn't been any activity around this topic, we're going to close the issue. Please submit a PR if you're interested in adding this functionality. Thank you!

**Closed by nparsons08** 2017-09-20 20:26 UTC
Labels: bug
