### ISSUE TITLE
Feeds are not refreshed

### ISSUE THREAD

**Issue by 2knarf** [GetStream/Winds#102] opened 2017-03-30 14:49 UTC
Hello, I'm trying the Demo, and when i add feeds it says: 

Feed missing

This happens on:

https://access.redhat.com/blogs/766093/feed

It does not always happen, but when I add feeds sucessfully they show up empty.

Any tips?

**Comment by nparsons08** [comment] 2017-09-20 21:45
@2knarf I attempted to reproduce the issue; however, I was unable to do so. Please see the attachment below. Due to the age of this issue, I'm going to go ahead and close it out. If you experience the issue again, please open up a new ticket outlining any errors that may appear in your console or network tab, along with your environment (OS, Browser, etc.). Thank you!

![2017-09-20 at 3 44 pm](https://user-images.githubusercontent.com/1328388/30669232-c2390882-9e1a-11e7-9d49-72ae71bb3102.png)

**Closed** 2017-09-20 21:46 UTC
