### ISSUE TITLE
Logged out every time I close the Winds program, and open it again.

### ISSUE THREAD

**Issue by OMGdaDPS** [GetStream/Winds#614] opened 2020-01-24 18:10 UTC
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

Have to log back in every time I close the program. I am running Ubuntu 19.10, and the snap version of Winds

### Steps to Reproduce

1. Open Winds
2. Log in to my account.
3. Close Winds
4. Re-open Winds and have to log back in, every time.
**Expected behavior:** To stay logged in.

**Actual behavior:** I am presented with a fresh "sign up" screen, as if I had never done it before on this same system, and same program.

**Reproduces how often:** 100% of the times tried.

### Versions
I cant get this info, because when I click the "about", nothing happens.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by mahboubii** [comment] 2020-01-24 19:08
duplicate of https://github.com/GetStream/Winds/issues/564

**Closed by mahboubii** 2020-01-24 19:08 UTC

**Comment by OMGdaDPS** [comment] 2020-01-24 19:15
I don't mean to sound negative in anyway shape or form, but how is it a duplicate when I am on a totally different operating system?

**Comment by mahboubii** [comment] 2020-01-24 19:22
@OMGdaDPS no worries, it's all Electron and I saw that you mentioned Ubuntu has the same issue on the other thread.

**Comment by OMGdaDPS** [comment] 2020-01-25 04:17
OHHHH! Ok, thanks!

**Comment by OMGdaDPS** [comment] 2020-01-28 04:08
Hey, so I have learned something new and didn't know if I should post it here or not. I am super tired, but I am going to get on it asap in the morning. 
  The gist of it is that, if I reboot my system, and THEN open Winds (snap version) I am logged back in. But if I close the program and the try to reopen it, I am logged out again. 
  But if I reboot and reopen the program, I am logged back in. 
What could I do to help figure this out? Any kind of commands that I can run and pipe into a text file or anything? I'm willing to be the test pig hahaha! I also have lots of hardware and plenty of memory fo VM's of various systems, if you need help, and also have lots of physical hardware to test on too.
 Just let me know.
 Love the program!
