### ISSUE TITLE
Make RSS feeds exportable to an importable backup file

### ISSUE THREAD

**Issue by anonsubmitter** [GetStream/Winds#55] opened 2016-11-22 23:35 UTC
I think it would be good if it was possible to export RSS feeds exportable to an importable backup file. But not to back up every single article that is posted in the RSS feeds, only to back up the RSS feeds themselves.

**Comment by nparsons08** [comment] 2016-11-22 23:36
Duplicate of https://github.com/GetStream/Winds/issues/1

**Comment by tschellenbach** [comment] 2016-11-23 03:22
Yes, this is a duplicate, but definitely something we'd like to add. A pull request implementing this will definitely be merged.

**Comment by nparsons08** [comment] 2016-11-28 18:57
https://www.npmjs.com/package/opml-generator looks like a good candidate for this task.

**Comment by nparsons08** [comment] 2017-09-20 20:16
Since there hasn't been any activity around this topic, we're going to close the issue. Please submit a PR if you're interested in adding this functionality. Thank you!

**Closed by nparsons08** 2017-09-20 20:16 UTC
Labels: enhancement, help wanted
