### ISSUE TITLE
Can't scroll down the page

### ISSUE THREAD

**Issue by bamadesigner** [GetStream/Winds#362] opened 2018-06-08 15:41 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

I can't scroll down the page. Looks like the culprit is that the .app selector has height set to 100vh.

I'm using Google Chrome.

### Steps to Reproduce

1. Visit any page.
2. Try to scroll down the page.

**Expected behavior:**
To be able to scroll down the page.

**Actual behavior:**
I'm stuck.

**Reproduces how often:** 
Every time.

### Versions

You can get this information from the manu. Winds > About Winds.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by nparsons08** [comment] 2018-06-08 21:40
@bamadesigner The issue you are describing is by design. Individual feeds are scrollable. Closing this out for now.

**Closed by nparsons08** 2018-06-08 21:40 UTC
Labels: bug, help wanted

**Comment by bamadesigner** [comment] 2018-06-08 22:19
You might want to consider re-thinking this approach. If your screen is not tall enough, there isn't much room to view what's inside the individual feeds as you scroll, since you can't scroll to make the elements above the feeds move out of the way.
